name: Renovate
on:
  schedule:
    - cron: '3 0 * * 1'
  workflow_dispatch:
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@v1
        with:
          private-key: ${{ secrets.private_key }}
          app-id: ${{ secrets.app_id }}
      - name: Checkout
        uses: actions/checkout@v4.2.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.2.10
        with:
          configurationFile: .github/configs/renovate-config.js
          token: '${{ steps.get_token.outputs.token }}'
